### ISSUE TITLE
Unable to find a specification for `RACarousel`

### ISSUE THREAD

**Issue by thunpisit** [Ramotion/circular-carousel#6]
Hi I'm on Xcode 10.2.1 and try to install RACarousel using CocoaPods but I encounter this error while installing. Then I search CocoaPods library but I am not able to find RACarousel

```
[!] Unable to find a specification for `RACarousel`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by realityworks** [comment]
@thunpisit the workspace is currently in development as is the repo, it should be ready for beta testing soon. The Pod is not ready yet.

**Comment by thunpisit** [comment]
Gotcha, thank you for the response.

**Comment by realityworks** [comment]
@thunpisit the library has been updated and linked to a pod now.

**Comment by thunpisit** [comment]
@realityworks When I try to install `pod 'CircularCarousel'` it said, 

```
[!] Unable to find a specification for `CircularCarousel`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

Maybe you have to update the README

**Comment by realityworks** [comment]
Have you done the pod repo update on your project? It is a new repository.
