### ISSUE TITLE
Doesn't work at all!

### ISSUE THREAD

**Issue by Gargo** [Ramotion/circular-carousel#8]
Falls on:
```
numberOfVisibleItems = Int(ceil(width / itemWidthWithSpacing)) + 2
```
The following callback method is even not called:
```
func carousel<CGFloat>(_ carousel: CircularCarousel, valueForOption option: CircularCarouselOption, withDefaultValue defaultValue: CGFloat) -> CGFloat {
	    switch option {
...
}
```

Maybe it is because I added carousel programmatically and with constraints

**Comment by realityworks** [comment]
Hello @Gargo given you have setup the carousel programmatically, can you confirm if you have setup delegate and datasource correctly?

How many items are you returning on `func numberOfItems(inCarousel carousel: CircularCarousel) -> Int`?

It could also be a problem with the delegate for the itemWidth. Given your <CGFloat> call does not get called. Does the callback work when you try the following :

```
    // MARK: -
    // MARK: CircularCarouselDelegate
    func carousel(_ carousel: CircularCarousel, valueForOption option: CircularCarouselOption, withDefaultValue defaultValue: Int) -> Int {
        if option == .itemWidth {
            return Int(carousel.bounds.width)
        }
        
        return defaultValue
    }
```

**Comment by realityworks** [comment]
@Gargo if you don't have anymore feedback on this I will close this issue.

**Comment by realityworks** [comment]
No response from OP and without more information I will close this.

**Comment by tylerschmitt** [comment]
I'm having this same issue. Is this possible to do programmatically? Thanks.

**Comment by maxmiranda** [comment]
Can comment on this, this happened for me when I didn't set a frame on my carousel card. I think there's some problem where the carousel(valueForOption) function is not properly setting the itemWidth on the carousel card, so we need to provide our own width of the actual item or else it errors out.
